# Generated by Django 4.2.7 on 2023-12-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klassy_cafe', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
