# Generated by Django 4.2.7 on 2023-12-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klassy_cafe', '0006_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pnumber',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
