# Generated by Django 4.2.7 on 2023-12-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klassy_cafe', '0007_rename_pnumber_contact_phone_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number_guests',
            field=models.IntegerField(null=True),
        ),
    ]
